### ISSUE TITLE
FAQ: precise memory tracking? performance impact?

### ISSUE THREAD

**Issue by jangorecki** [atheriel/xrprof#18]
I would like to suggest make a FAQ.md (or similar) to put common questions there.
I have two for now:
- does it handle `malloc` rather than only `R_alloc` like R's profiling?
- how does it affect performance of the script being debugged? both time and space

**Comment by atheriel** [comment]
An appropriate place to put this would be the `README`, currently. To answer you specific questions:

1. `xrprof` doesn't do memory profiling like `Rprof()` at this time (or likely ever).
2. It depends on many samples you are taking (frequency), whether you are using mixed-mode profiling (which has additional overhead), and the specific workload. It's also a bit hard to measure, since it requires a notion of throughput in the original script. I would advise experimenting with these settings to see how it affects your particular workload, but usually the impact is in the 0-5% range.
