### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by JZL** [atheriel/xrprof#22]
Hi,

I just wanted to thank you for making this tool! A similar tool, [py-spy](https://github.com/benfred/py-spy), has become invaluable for me and R+R-studio does even more mysterious things than python so this is really great.

The default stdout already goes a long way for what I'd like but one additional useful thing py-spy does is have a psuedo-`top` view to see an always-updating stack trace with collating %Time (like [this](https://github.com/benfred/py-spy/blob/master/images/console_viewer.gif)). Is that something you'd be interested in? I could look at working on a PR, although no promises on a timeline

(It is unfortunate you are deep on the second page of google when I looked up "R profiler" because I was looking for this months ago. Because you might laugh, I was about to bite the bullet and write my own very hacky version so was looking up '`process_vm_readv` R' and then you came up first link! Although that is a pretty esoteric search request)

**Comment by atheriel** [comment]
I'm glad it's been a useful project for you. Sorry it was hard to find -- it's a fairly new project, I just gave the first official public announcement [at RStudio conf in January](https://www.rstudio.com/resources/rstudioglobal-2021/introducing-xrprof-a-new-way-to-profile-r/).

A major goal of this project is compatibility with R's existing `Rprof()`-based tools, which is why the default output looks as it does. That said, I'd be open to additional output representations, though I've never really though about how a top-like interface could be implemented.

As an aside: `py-spy` was a major source of inspiration for this tool, especially in the approach to mixed R and C/C++ profiling. I should really call it out in the README.

**Comment by JZL** [comment]
So this is mostly anecdotal but I've had xrprof running pretty much nonstop since I found it on a variety of high-memory and many-multi-core R code (on both rstudio and jupyter IRKernel). It is truly invaluable for manual profiling of code

It was mostly set-and-forget but a good number of times R would be hanging (often just with `<TopLevel>`) and I couldn't figure out what was holding it up. `htop` would show 100% kernel activity on one core. Sometimes (but not all), quitting out of xrprof actually helped it move on to the next thing. Also I somewhat consistently found that with large `plan(multicore)` splits, sometimes when it was splitting up the jobs with xrprof on, it would hang, only stopping when I quit xrprof.

My hacky solution was to `watch -n 3 xrprof -p __ -d 0.1` where each instead of xrprof polling, I used `watch`. It is all anecdotal but I haven't had it happen since

Also small inconsequential annoyance but if I interrupted the IRkernel in jupyter or 'stop'ed in rstudio, the xrprof would also quit with `fatal: Unexpected stop signal in remote process: 2.`. Is that expected?`/unavoidable

(I can open a new issue but it is all pretty anecdotal/inconsequential)

**Comment by atheriel** [comment]
I honestly don't know what will happen with multicore splits -- I'd never thought about how to handle parallel execution correctly, and am not familiar with what actually occurs in those cases. You can for sure open a new issue and I will see what I can find.

~~The signal issue with Jupyter is also a legitimate, unrelated issue. `xrprof` expects certain signals for normal R sessions, but these may be different when running R from a notebook -- I would like to support this usecase if possible, so this is basically a bug. But again, I'm not sure what Jupyter is actually doing here, as I am unfamiliar with that particular technology.~~

Edit: on reflection, the signal thing is probably expected behaviour. If you stop the R process, there is nothing to profile, so `xrprof` should probably exit.

**Comment by JZL** [comment]
For the multicore splits, it does basically everything I expect. Which is to say, since I'm usually following the pid of the parent, it shows those parent's fn calls (and if I do it for the child sessions/multicore split's pid I can even look into their calls). Even if you could collate all the child processes's fns, I'm not sure I'd even want that. Really what was difficult was the (hearsay) observation that it sometimes held up processing. My mental model was that it was entirely passively observing the execution, so I didn't know if it was even possible for it to interfere (keeping a file descriptor open or something strange?). It definitely wasn't consistent but also not that rare in all-R workday

For the signals, two things. One is that this was also the case if I click the stop=stop sign icon in rstudio. I'm happy to deal with it as expected behavior, but for what it's worth, the rsession (= 'process'?) is still up, it just interrupted the execution. So the pid is still valid when I re-run xrprof with the same args
